// Parses the legacy Kotlin server's `data.sql` (stored in the neighbouring
// differ-server repo) and emits a D1-friendly SQL file that flattens each
// puzzle's `differences` JSONB shape-wrapper into a plain `RectArea[]` JSON.
//
// Usage:
//   node --experimental-strip-types scripts/import-puzzles.ts
//     [--input=<path>] [--output=scripts/seed/puzzles.sql]
//
// Then apply with:
//   wrangler d1 execute differ --local  --file=scripts/seed/puzzles.sql
//   wrangler d1 execute differ --remote --file=scripts/seed/puzzles.sql

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";

type LegacyShape = {
  type: string;
  areas: Array<{ id: string; sp: { x: number; y: number }; w: number; h: number }>;
};

const args = Object.fromEntries(
  process.argv.slice(2).map((a) => {
    const m = a.match(/^--([^=]+)(?:=(.*))?$/);
    return m ? [m[1]!, m[2] ?? "true"] : [a, "true"];
  }),
);

const DEFAULT_INPUT = resolve(
  process.cwd(),
  "../../../differ-server/src/main/resources/db/data.sql",
);
const input = (args.input as string | undefined) ?? DEFAULT_INPUT;
const output =
  (args.output as string | undefined) ?? resolve(process.cwd(), "scripts/seed/puzzles.sql");

const sql = readFileSync(input, "utf8");

// Row format:
//   INSERT INTO puzzles (id, differences, path, extension) VALUES ('<id>', '<json>', '<path>', '<ext>');
const rowRe =
  /INSERT INTO puzzles \(id, differences, path, extension\) VALUES \('([^']+)', '(.+?)', '([^']+)', '([^']+)'\);/g;

const rows: Array<{ id: string; differences: string; path: string; extension: string }> = [];

for (const m of sql.matchAll(rowRe)) {
  const [, id, diffJson, path, extension] = m as unknown as [
    string,
    string,
    string,
    string,
    string,
  ];
  const shapes = JSON.parse(diffJson) as LegacyShape[];
  // Flatten all areas from all shapes (legacy used polygon/rect but only rect shipped).
  const areas = shapes.flatMap((s) => s.areas);
  rows.push({
    id,
    differences: JSON.stringify(areas),
    path,
    extension,
  });
}

if (rows.length === 0) {
  console.error(`No puzzle rows matched in ${input}`);
  process.exit(1);
}

function esc(s: string): string {
  return s.replace(/'/g, "''");
}

const statements: string[] = [];
statements.push("-- Generated by import-puzzles.ts");
statements.push("DELETE FROM puzzles;");
for (const r of rows) {
  statements.push(
    `INSERT INTO puzzles (id, differences, path, extension) VALUES ('${esc(r.id)}', '${esc(r.differences)}', '${esc(r.path)}', '${esc(r.extension)}');`,
  );
}

mkdirSync(dirname(output), { recursive: true });
writeFileSync(output, statements.join("\n") + "\n");
console.log(`Wrote ${rows.length} puzzles to ${output}`);
